### ISSUE TITLE
Question - Does this project support macOS?

### ISSUE THREAD

**Issue by yuerem** [Shahzainali/Wireguardkit#1]
Thank you for this wonderful project. 
It seems to support iOS, but does it also support macOS? 
I tried building and running the project on a macOS system and, while there were no error messages, nothing happened when I attempted to run it. Any advice or guidance would be greatly appreciated.

**Comment by Shahzainali** [comment]
Hi, it will but you need to repeat some steps:
1: Add one more external target. WireguardGoBridgeMacOS
2: Switch to "Build Settings" and find SDKROOT. Type in macosx fos macos.
3: In NetworkExtenstion "Dependencies"  section and hit "+" to add WireGuardGoBridgeMacOS

I have got these steps from the official repo, I haven't tried. but I am sure it will work as explained above.

**Comment by yuerem** [comment]
@Shahzainali 
I tried again today following the guide from the beginning, but I encountered an error and could not build the project.
Could you provide any advice?

Chip: Apple M2
OS: 14.4
Xcode: 15.3

ERROR:
```
Undefined symbols for architecture arm64:
  "_darwin_arm_init_mach_exception_handler", referenced from:
      _x_cgo_init in libwg-go.a[arm64][9](000006.o)
  "_darwin_arm_init_thread_exception_port", referenced from:
      _threadentry in libwg-go.a[arm64][9](000006.o)
      _x_cgo_init in libwg-go.a[arm64][9](000006.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by evan802399** [comment]
@Shahzainali 
HI, i modify app identifier to mine, then run the demo,  get some errors
![image](https://github.com/user-attachments/assets/c7b2e01b-763d-44b3-81b9-678227fea584)

can you give me any advice ?

**Comment by evan802399** [comment]
> @Shahzainali HI, i modify app identifier to mine, then run the demo, get some errors ![image](https://private-user-images.githubusercontent.com/5545879/360280673-c7b2e01b-763d-44b3-81b9-678227fea584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTk1NTksIm5iZiI6MTcyNDI5OTI1OSwicGF0aCI6Ii81NTQ1ODc5LzM2MDI4MDY3My1jN2IyZTAxYi03NjNkLTQ0YjMtODFiOS02NzgyMjdmZWE1ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDQwMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhjZTA5MmUxYjk4NzlhNzY2MWJiZWYwOTk5OWUwM2VjOGM1ODZlZGVjNDMyZTRmNmExMTYwZTY3MDU5N2JiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bgppbYzakrasCqr15uiW6LEarsfLX5qMmpCECpAn_S8)
> 
> can you give me any advice ?

Chip: Apple M1
OS: 14.4
Xcode: 15.4

**Comment by Harisghanchi** [comment]
> Hi, it will but you need to repeat some steps: 1: Add one more external target. WireguardGoBridgeMacOS 2: Switch to "Build Settings" and find SDKROOT. Type in macosx fos macos. 3: In NetworkExtenstion "Dependencies" section and hit "+" to add WireGuardGoBridgeMacOS
> 
> I have got these steps from the official repo, I haven't tried. but I am sure it will work as explained above.

it works i have tried have succesully build the macos project  m1 xcode 15.4

**Comment by Shahzainali** [comment]
@Harisghanchi Perfect, Thanks for the update.

**Comment by Shahzainali** [comment]
It is working on macos.

**Comment by Harisghanchi** [comment]
hello wireguard is working on ios perfect but on macos wireguard is connecting succesfully but it stops internet browsing when connects to wireguard but i have tried using wirguard app with same config file its working

**Comment by Shahzainali** [comment]
Hi, can you please share NE logs.
