### ISSUE TITLE
 Showing Recent Issues Internal inconsistency error: never received target ended message for target ID '5' (in target 'WireguardGoBridge' from project 'Wireguardkit'). Build again to continue.

### ISSUE THREAD

**Issue by AdnanAliShabir** [Shahzainali/Wireguardkit#2]
Thank you for this great repository.

I'm trying to compile it in Xcode 15 and 16, but I'm encountering failures.

Could you please let me know if I'm overlooking anything?

Thanks!

**Comment by Shahzainali** [comment]
delete deriveddata folder, clean the project, and try to build again.

**Comment by AdnanAliShabir** [comment]
I added this repo https://github.com/upvpn/wireguard-apple, It compiled but on VPN profile it shows "Update Required". 

Do you know why it is showing ?

**Comment by Shahzainali** [comment]
Yes, change the minimum deployment of your Network extension target.

**Comment by AdnanAliShabir** [comment]
I tried to set the 15.6 and 18.0 but it does not works. 

I matched it with App Target.

**Comment by Shahzainali** [comment]
hmm, try cleaning project, this error is due to minimum deployment.

**Comment by AdnanAliShabir** [comment]
What should be the minimum deployment ? I tried to clean and delete derived data.

**Comment by Shahzainali** [comment]
set both to 15.0 and try

**Comment by AdnanAliShabir** [comment]
Not works. Any other reason of this issue ? 



Sent from Yahoo Mail for iPhone


On Friday, October 11, 2024, 7:06 PM, Shahzain Ali ***@***.***> wrote:




set both to 15.0 and try

**Comment by AdnanAliShabir** [comment]
I means is there related to the app store account or any other possible reason.

**Comment by Shahzainali** [comment]
not related to app store account.

**Comment by Yan-jinwei** [comment]
Hello, I am running under Xcode15 and 16 and I have the same problem, have you solved it?

**Comment by AdnanAliShabir** [comment]
Hi, I implemented it in a new project, and it started working. I’m not entirely sure what the issue was initially.

**Comment by Shahzainali** [comment]
Good to know that you have fixed the issue :)

**Comment by Shahzainali** [comment]
Not an issue.
